[broker]
address = "ndlmusrkafka.isis.cclrc.ac.uk"
username = "processing"
password = "<processing password>"
group = "frame-assy"

[topics]
source = "events-in"
destination = "events-preproc-1"

[processing]
frame_timeout = 500

[[digitisers]]
id = 0
